# Streamlit Secrets Configuration for NXTRIX CRM
# Place this content in your .streamlit/secrets.toml file

# === SUPABASE CONFIGURATION ===
# Get these from your Supabase project settings
SUPABASE_URL = "https://your-project-id.supabase.co"
SUPABASE_KEY = "your-anon-public-key-here"

# === OPENAI CONFIGURATION ===
# For AI features (optional)
OPENAI_API_KEY = "your-openai-api-key-here"

# === EMAIL CONFIGURATION ===
# For email notifications (optional)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "your-email@gmail.com"
SMTP_PASSWORD = "your-app-password"

# === SMS CONFIGURATION ===
# For SMS features (optional)
TWILIO_ACCOUNT_SID = "your-twilio-account-sid"
TWILIO_AUTH_TOKEN = "your-twilio-auth-token"
TWILIO_PHONE_NUMBER = "+1234567890"

# === STRIPE CONFIGURATION ===
# For payment processing (optional)
STRIPE_PUBLISHABLE_KEY = "pk_test_your_stripe_key"
STRIPE_SECRET_KEY = "sk_test_your_stripe_secret"
STRIPE_WEBHOOK_SECRET = "whsec_your_webhook_secret"

# === PRODUCTION SETTINGS ===
[production]
debug = false
log_level = "INFO"

# === DEMO MODE SETTINGS ===
[demo]
enabled = true
demo_email = "demo@nxtrix.com"
demo_password = "demo123"
admin_email = "admin@nxtrix.com"
admin_password = "admin123"